# MIT License
#
# Copyright (c) 2021 GitHub, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # See https://github.com/actions/starter-workflows/blob/main/pages/nextjs.yml#L56-L63.
          static_site_generator: next
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install dependencies
        run: npm ci

      - name: Install SVGO
        run: npm install -g svgo

      # `svgo.config.js` overrides `removeEditorsNSData` to `false`. This is
      # useful for modifying SVGs, but not needed for rendering. That is why we
      # remove it here.
      - name: Remove `svgo.config.js`
        run: rm -f svgo.config.js
      - name: Optimize SVGs
        run: svgo --folder=public --multipass

      - name: Build with Next.js
        run: npx --no-install next build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          path: ./out

  # If, for some reasons, merging this workflow with the build one is required,
  # make sure to run Prettier BEFORE `actions/configure/pages` as it will modify
  # `next.config.js`.
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Show Prettier version
        run: npx prettier --version
      - name: Run Prettier
        run: npx prettier --check .

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Show ESLint version
        run: npx eslint --version
      - name: Run ESLint
        run: npx eslint .

  check_svg_size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install SVGO
        run: npm install -g svgo
      - name: Check if SVGs are compressed
        run: find ./**/*.svg -print0 | xargs -0 -I {} sh -c '[ $(svgo --output - --multipass {} | wc -c) -eq $(wc -c < {}) ] || {echo "Run `svgo --multipass {}` to optimize it."; false;}'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build, prettier, eslint, check_svg_size]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
